	<!-- <p>View script for controller <b>Categories</b> and script/action name <b>list</b></p> -->

<div class="row">
            <div class="col-lg-12">
                <h1 class="page-header color-horg">Category
                    <small>category Type</small>
                </h1>
                     <ol class="breadcrumb alert alert-info alert-warning">
                           <li class="active ">
                           <i class="fa fa-dashboard"></i> Category
                         </li>
                    </ol>
            </div>
        </div>
<div >
    <?php if($this->identity->user_type=="admin"){?>


         <div class="row">
            <?php
            if(!empty($this->category_data)) var_dump ($this->category_data);
            for ($i=0;$i<count($this->categories); $i++)
             { ?>
       
            <div class="col-md-4 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="../img/logo.jpg" alt="">
                </a>
                <h3 class="">
                    <a href="#" class="btn btn-warning active" ><?php echo $this->categories[$i]['name']?></a>
                </h3>
          <ul class="list-group">
            <li class="list-group-item "><?php echo $this->categories[$i]['name']?>
            </li>
          
            <li class="list-group-item"> <?php echo "<a href='delete/id/".$this->categories[$i]['id']."'>Delete</a>"?>
            </li> 
    

          </ul>
            </div>
            
        

       <?php } ?>
    
<div  role="form" class="col-lg-12">
    <div class="form-group has-warning">
        <?php echo $this->form; ?>
       </div>
   </div>
   </div> 
    <?php  }

    else 
        {echo "<div class=\"row\">";
            for ($i=0;$i<count($this->categories); $i++)
             {?>
                            <div class="col-md-4 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="../img/logo.jpg" alt="">
                </a>
                <h3 class="">
                    <a href="#" class="btn btn-warning active" ><?php echo $this->categories[$i]['name'];?></a>
              </h3>

              </div>
<?php
               
       
            }
        }
    
    
    ?>
</div>

