<!-- <br /><br />
<div id="view-content">
	
</div> -->

<div class="row">
            <div class="col-lg-12">
                <h1 class="page-header color-horg">Material
                    <small>Add Materialtype</small>
                </h1>
                     <ol class="breadcrumb alert alert-info alert-warning">
                           <li class="active ">
                           <i class="glyphicon glyphicon-floppy-disk"></i> Materials
                         </li>
                    </ol>
            </div>
        </div>

<div>
<div>
                 <div class="row">
                    <div class="col-lg-12">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover table-striped">
                                <thead>

                                    <tr>
                                        <th>Type Name </th>
                                        <th>Edit Course </th>
                                        <th>Delete Course </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                                <?php
                                                for ($i=0;$i<count($this->types); $i++)
                                                 {
                                                
                                                    echo "<tr class=\"warning\">";
                                                    echo "<td>".$this->types[$i]['type_name']."</td>";
                                                    echo "<td><a href='add/id/".$this->types[$i]['id']."'class=\"btn btn-sm btn-warning\">Edit</a></td>";
                                                    echo "<td><a href='delete/id/".$this->types[$i]['id']."'class=\"btn btn-sm btn-danger\"> Delete</a></td>";
                                                
                                                echo "</tr>";
                                           
                                                }
                                                 ?>
                                     </tbody>
                            </table>
                        </div>
                    </div>
                </div>    
        <div class="row">
          <div class="col-lg-12">
                 <br/>
             <div class="panel panel-warning">
             <div class="panel-heading">
    <?php echo $this->form; ?>
    </div>
    </div>
    </div>
    </div>
</div>
