<div id="view-content">
    <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header color-horg">Materials
                    <small>Add Materials</small>
                </h1>
                     <ol class="breadcrumb alert alert-info alert-warning">
                           <li class="active ">
                           <i class="glyphicon glyphicon-text-height"></i> Materials
                         </li>
                    </ol>
            </div>
        </div>



	<div class="row">
	      <div class="col-lg-12">
                 <br/>
             <div class="panel panel-warning">
             <div class="panel-heading">
			<?php echo $this->form;?>
			</div>
			</div>
		</div>
	</div>
</div>

