<!-- <div id="view-content">
	<p>View script for controller <b>Materials</b> and script/action name <b>list</b></p>
</div> -->

<div class="row">
            <div class="col-lg-12">
                <h1 class="page-header color-horg">Material
                    <small>Materials Add</small>
                </h1>
                     <ol class="breadcrumb alert alert-info alert-warning">
                           <li class="active ">
                           <i class="glyphicon glyphicon-floppy-disk"></i> Materials
                         </li>
                    </ol>
            </div>
        </div>

<div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>Material Name</th>
                                        <th>Course Name</th>
                                        <th>Material Type </th>
                                        <th>Comment </th>
                                        <th>Download </th>
                                       <?php 
                                        if($this->identity->user_type=="admin")
                                        {?>
                                        <th>Edit Material </th>
                                        <th>Delete Material </th>
                                        <?php }  ?>
                                    </tr>
                                </thead>
                                <tbody>

                                     <?php
                                        
                                        for ($i=0;$i<count($this->materials); $i++)
                                        {
                                            echo "<tr class=\"warning\">";
                                            echo "<td>".$this->materials[$i]['name']."</td>";
                                            echo "<td>".$this->courses[$i]."</td>";
                                            echo "<td>".$this->types[$i]."</td>";       
                                            echo "<td><a href='http://localhost/mysite/public/comments/list/mid/".$this->materials[$i]['id']."'class=\"btn btn-sm btn-primary\">Comments</a></td>";
                                            echo "<td><a href='#/id/".$this->materials[$i]['id']."'class=\"btn btn-sm btn-success\"> Download</a></td>";
                                            if($this->identity->user_type=="admin")
                                                {
                                                echo "<td><a href='edit/id/".$this->materials[$i]['id']."'class=\"btn btn-sm btn-warning\">Edit</a></td>";
                                                echo "<td><a href='delete/id/".$this->materials[$i]['id']."'class=\"btn btn-sm btn-danger\"> Delete</a></td>";
                                                }

                                            echo "</tr>";
                                   
                                        }
                                 ?>


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
