
<?php if($this->success){ ?>
    <div class="alert alert-success">
        Regesteration complete Successfully.
    </div>
<?php } ?>


        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header color-horg">Register
                    <small>Register Form</small>
                </h1>
                     <ol class="breadcrumb alert alert-info alert-warning">
                           <li class="active ">
                           <i class="fa fa-fw fa-edit"></i> Register
                         </li>
                    </ol>
            </div>
        </div>

        <div class="row">

                <div  role="form" class="col-lg-12">

    <div class="form-group has-warning">
        	<?php echo $this->form; ?>
</div>