<br /><br />
<?php if($this->success){ ?>
    <div class="alert alert-success">
       Profile complete Successfully.
    </div>
<?php } ?>


<!--   <p>View script for controller <b>Users</b> and script/action name <b>edit</b></p> -->
<div id="view-content">
<div class="row">
            <div class="col-lg-12">
                <h1 class="page-header color-horg">Profile
                    <small>User Profile</small>
                </h1>
                     <ol class="breadcrumb alert alert-info alert-warning">
                           <li class="active ">
                           <i class="glyphicon glyphicon-floppy-disk"></i> Profile
                         </li>
                    </ol>
            </div>
        </div>


<div>
               <div class="row clearfix">

        <div class="col-md-12 column">
	<?php echo $this->form; ?>
</div>
</div>
</div>