<!-- <br /><br />
<div id="view-content">
	<p>View script for controller <b>Users</b> and script/action name <b>list</b></p>
</div> -->
<div class="row">
            <div class="col-lg-12">
                <h1 class="page-header color-horg">Users
                    <small>user add</small>
                </h1>
                     <ol class="breadcrumb alert alert-info alert-warning">
                           <li class="active ">
                           <i class="glyphicon glyphicon-floppy-disk"></i> Materials
                         </li>
                    </ol>
            </div>
        </div>

 <div class="row">
                    <div class="col-lg-12">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>User Name</th>
                                        <th>EMAil</th>
                                        <th>User Type </th>
                                        <th>Activetion </th>
                                       <?php 
                                        if($this->identity->user_type=="admin")
                                        {?>
                                        <th>Edit user </th>
                                        <th>Delete user </th>
                                        <?php }  ?>
                                    </tr>
                                </thead>
                                <tbody>
                    

<?php  
       for($i=0; $i<count($this->users); $i++)
        {
            echo "<tr class=\"warning\">";
            echo "<td>".$this->users[$i]['f_name']." ".$this->users[$i]['l_name']."</td>";
            echo "<td>".$this->users[$i]['username']."</td>";
            echo "<td>".$this->users[$i]['user_type']."</td>";  
            echo "<td>";
            if($this->users[$i]['active'])
                echo "Active";
            else
                echo "Not Active";  
                
            echo "</td>"; 
            echo "<td><a href='edit/id/".$this->users[$i]['id']."'class=\"btn btn-sm btn-warning\">Edit </a></td>";
            echo "<td><a href='delete/id/".$this->users[$i]['id']."'class=\"btn btn-sm btn-danger\">Delete</a></td>";
            echo "</tr>";
            
        }	
	
?>


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>