<div id="view-content">
	<!-- <p>View script for controller <b>Requests</b> and script/action name <b>add</b></p> -->
	<div class="row">
            <div class="col-lg-12">
                <h1 class="page-header color-horg">Requests
                    <small>Add Requests</small>
                </h1>
                     <ol class="breadcrumb alert alert-info alert-warning">
                           <li class="active ">
                           <i class="fa fa-fw fa-edit"></i> Request
                         </li>
                    </ol>
            </div>
        </div>

<div>
        <div class="row">
          <div class="col-lg-12">
                 <br/>
             <div class="panel panel-warning">
             <div class="panel-heading">
             <div class="form-group has-warning">
        <?php echo $this->form;?>
       </div>
       </div>
       </div>
       </div>
       </div>
</div>