
<!DOCTYPE html>
<html lang="en">

<head>

 <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/bootstrap.min.css')?>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/sb-admin.css')?>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/font-awesome.min.css')?>



</head>

<body>

<div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="navbar-header color-horg">
                <button type="button" class="navbar-toggle " data-toggle="collapse" data-target=".navbar-ex1-collapse">

                </button>
                <a class="navbar-brand color-horg" href="#">SLMS</a>
            </div>
                <ul class="nav navbar-right top-nav">
                
                <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>&nbsp;wellcome&nbsp;<?php echo $this->identity->f_name ?><b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a role="menuitem" tabindex="-1"href="<?php echo $this->baseUrl() ?>/users/edit"><i class="fa fa-user"></i> Profile</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->baseUrl() ?>/users/list"><i class="fa fa-fw fa-gear"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="<?php echo $this->baseUrl() ?>/users/logout"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                            <li >
                        <a href="#" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-dashboard"></i> Category <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo" class="collapse">
                    <li <?php if($this->page_title === "category")echo 'class="active"'; ?>>
                        <a href="<?php echo $this->baseUrl() ?>/categories/list"></i> categList</a>
                    </li>

                        </ul>
                    </li>

                    <li >
                        <a href="#" data-toggle="collapse" data-target="#demoo"><i class="glyphicon glyphicon-book"></i> Materials <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demoo" class="collapse">
                         <?php
                          if($this->identity->user_type=="admin")
                                              {?>

                    <li  >

                        <a href="<?php echo $this->baseUrl() ?>/materials/add"></i> add</a>
                    </li>

                    <?php }?>
                    <li <?php //if($this->page_title === "category")echo 'class="active"'; ?>>

                        <a href="<?php echo $this->baseUrl() ?>/materials/list"></i> list</a>
                    </li>
                                     <?php
                          if($this->identity->user_type=="admin")
                                              {?>
                    <li <?php //if($this->page_title === "category")echo 'class="active"'; ?>>

                        <a href="<?php echo $this->baseUrl() ?>/materialtype/add"></i> types</a>
                    </li>
                    <?php }?>

                        </ul>
                    </li>
                                <?php
                          if($this->identity->user_type=="admin")
                                              {?>
                     <li>
                        <a href="<?php echo $this->baseUrl() ?>/comments/list"><i class="fa fa-fw fa-edit"></i> Comments</a>
                    </li>
                    <?php }?>

                           <?php
                          if($this->identity->user_type=="admin")
                                              {?>

                        <li >
                        <a href="#" data-toggle="collapse" data-target="#demooo"><i class="glyphicon glyphicon-plus-sign"></i> Courses <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demooo" class="collapse">
                    <li >
                        <a href="<?php echo $this->baseUrl() ?>/courses/list"></i> list of course</a>
                    </li>
                     <li >
                        <a href="<?php echo $this->baseUrl() ?>/courses/add"></i> add course</a>
                    </li>

                        </ul>
                    </li>

                    <?php }?>

                           <?php
                           // var_dump($this->identity);  if($this->identity->user_type=="admin")
                                              {?>

                 <li >
                        <a href="#" data-toggle="collapse" data-target="#demooo1"><i class="fa fa-fw fa-edit"></i> Request <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demooo1" class="collapse">
                             <?php
                          if($this->identity->user_type=="admin")
                                              {?>
                    <li >
                        <a href="<?php echo $this->baseUrl() ?>/requests/list"></i> list Request</a>
                    </li>
                     <?php }?>
                     <li >
                        <a href="<?php echo $this->baseUrl() ?>/requests/add"></i> add Request</a>
                    </li>

                        </ul>
                    </li>
   <?php
                          if($this->identity->user_type=="admin")
                                              {?>
                            <li >
                        <a href="#" data-toggle="collapse" data-target="#demooo2"><i class="glyphicon glyphicon-user"></i> USERS <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demooo2" class="collapse">
                    <li >
                        <a href="<?php echo $this->baseUrl() ?>/users/list"></i> list users</a>
                    </li>
                     <li >
                        <a href="<?php echo $this->baseUrl() ?>/users/add"></i> add user</a>
                    </li>
                    
                        </ul>
                    </li>

<?php }?>
                    <?php }?>

              </ul>
            </div>      
       </nav>
    <div id="page-wrapper">
<?php echo $this->layout()->content; ?>
    </div>
</div>
    <!-- /#wrapper -->


<script src="<?php echo $this->baseUrl() ?>/js/jquery.js"></script>
<script src="<?php echo $this->baseUrl() ?>/js/bootstrap.min.js"></script>
</body>

</html>

