<div id="view-content">
	<!-- <p>View script for controller <b>Comments</b> and script/action name <b>list</b></p> -->
    <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header color-horg">Comments
                    <small>all comments</small>
                </h1>
                     <ol class="breadcrumb alert alert-info alert-warning">
                           <li class="active ">
                           <i class="glyphicon glyphicon-text-height"></i> Comments
                         </li>
                    </ol>
            </div>
        </div>




<div class="row">
        <?php
         
        for($i=0;$i<count($this->comments);$i++)
        { ?>
                 <div class="col-lg-6">
                 <br/>
                <div class="panel panel-warning">
                <div class="panel-heading">
                <?php 

            echo $this->identity->username."<h5 class=\"panel-title\">".$this->comments[$i]['cdate']."</h5>";
             echo "</div>";
             
           // echo "<textarea disabled rows=10 cols=20>".$this->comments[$i]['body']."</textarea>";
            $body = new Zend_Form_Element_Textarea('body'); 
            $body->setLabel("Comment:");
            $body->setRequired();
            $body->setValue($this->comments[$i]['body']);
            $body->setAttrib("rows", "5");
            $body->setAttrib("disabled",true);
            echo "<div class=\"panel-body\">";
            echo $body->getValue();
            echo "</div>";
            echo "</div>";

            if($this->identity->user_type=="admin")
            {

             echo "<a href='list/cid/".$this->comments[$i]['id']."' class=\"btn btn-sm btn-warning\">Edit</a>&nbsp;&nbsp;";

             echo "<a href='delete/cid/".$this->comments[$i]['id']."'class=\"btn btn-sm btn-danger\"> Delete</a>";
            }
                 echo "</div>";
            
        }
        

        
        ?>
               
        <hr>
        <div  role="form" class="col-lg-12">
        <hr>
        <br/>
             <ol class="breadcrumb alert alert-info alert-warning">
                           <li class="active ">
                           <i class="glyphicon glyphicon-text-height"></i> Add Comment
                         </li>
             </ol>
    <div class="form-group has-warning">
        <?php echo $this->form; ?>
       </div>
   </div>
</div>

