
<div id="view-content">
	<!-- <p>View script for controller <b>Courses</b> and script/action name <b>list</b></p> -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header color-horg">Coureses
                    <small>Coureses list</small>
                </h1>
                     <ol class="breadcrumb alert alert-info alert-warning">
                           <li class="active ">
                           <i class="glyphicon glyphicon-screenshot"></i> Courses
                         </li>
                    </ol>
            </div>
        </div>
</div>
<div class="row">

            <?php
            
            for ($i=0;$i<count($this->courses); $i++)
            {?>
            
            <div class="col-lg-12">
            <br/>
                        <div class="panel panel-warning">
                            <div class="panel-heading">
                                <h3 class="panel-title"><?php echo $this->courses[$i]['name']; ?></h3>
                            </div>
                            <div class="panel-body">
                                Category Name : <?php echo $this->categories[$i]; ?> <br/>
                                Coures HR: <?php echo $this->courses[$i]['hours'];?>
                            </div>

             </div>
                            <?php
                    if($this->identity->user_type=="admin")
            {

             echo "<a href='edit/id/".$this->courses[$i]['id']."' class=\"btn btn-sm btn-warning\">Edit</a>&nbsp;&nbsp;";

             echo "<a href='delete/id/".$this->courses[$i]['id']."'class=\"btn btn-sm btn-danger\"> Delete</a>";
            }?>
               </div>         
       
            <?php }?>

</div>
